import Foundation

enum KeyKind { case kbd, con }

struct KeyOption: Hashable {
    let label: String
    let kind: KeyKind
    let expr: String
    let legend: String
}

struct Modifier {
    let symbol: String
    let name: String
    let expr: String
}

let modifiers: [Modifier] = [
    Modifier(symbol: "⌃", name: "control", expr: "KBD_KEY_LEFT_CTRL"),
    Modifier(symbol: "⌥", name: "option", expr: "KBD_KEY_LEFT_ALT"),
    Modifier(symbol: "⇧", name: "shift", expr: "KBD_KEY_LEFT_SHIFT"),
    Modifier(symbol: "⌘", name: "command", expr: "KBD_KEY_LEFT_GUI"),
]

let keyOptions: [KeyOption] = {
    var opts: [KeyOption] = []
    for ch in "abcdefghijklmnopqrstuvwxyz0123456789" {
        opts.append(KeyOption(label: String(ch), kind: .kbd, expr: "'\(ch)'",
                              legend: String(ch).uppercased()))
    }
    let specials: [(String, String, String)] = [
        ("Space", "' '", "␣"), ("Enter", "KBD_KEY_RETURN", "⏎"),
        ("Escape", "KBD_KEY_ESC", "⎋"), ("Tab", "KBD_KEY_TAB", "⇥"),
        ("Backspace", "KBD_KEY_BACKSPACE", "⌫"), ("Delete", "KBD_KEY_DELETE", "⌦"),
        ("Up", "KBD_KEY_UP_ARROW", "↑"), ("Down", "KBD_KEY_DOWN_ARROW", "↓"),
        ("Left", "KBD_KEY_LEFT_ARROW", "←"), ("Right", "KBD_KEY_RIGHT_ARROW", "→"),
        ("Home", "KBD_KEY_HOME", "↖"), ("End", "KBD_KEY_END", "↘"),
        ("Page Up", "KBD_KEY_PAGE_UP", "⇞"), ("Page Down", "KBD_KEY_PAGE_DOWN", "⇟"),
    ]
    for (label, expr, legend) in specials {
        opts.append(KeyOption(label: label, kind: .kbd, expr: expr, legend: legend))
    }
    for n in 1...24 {
        opts.append(KeyOption(label: "F\(n)", kind: .kbd, expr: "KBD_KEY_F\(n)", legend: "F\(n)"))
    }
    let media: [(String, String, String)] = [
        ("Play/Pause", "0xCD", "⏯"), ("Next Track", "CON_MEDIA_NEXT", "⏭"),
        ("Previous Track", "CON_MEDIA_PREV", "⏮"), ("Volume Up", "CON_VOL_UP", "VOL+"),
        ("Volume Down", "CON_VOL_DOWN", "VOL−"), ("Mute", "CON_VOL_MUTE", "MUTE"),
    ]
    for (label, expr, legend) in media {
        opts.append(KeyOption(label: label, kind: .con, expr: expr, legend: legend))
    }
    return opts
}()

func keyOption(_ label: String) -> KeyOption {
    keyOptions.first { $0.label == label } ?? keyOptions[0]
}

enum KeySpecMode: String { case key, text }

struct KeySpec {
    var mode: KeySpecMode = .key
    var mods: [Bool] = [false, false, false, false]
    var keyLabel: String = "a"
    var text: String = ""

    var legend: String {
        if mode == .text {
            let flat = text.replacingOccurrences(of: "\n", with: "⏎")
            if flat.isEmpty { return "…" }
            return "“" + flat.prefix(7) + (flat.count > 7 ? "…”" : "”")
        }
        let opt = keyOption(keyLabel)
        let prefix = opt.kind == .con ? "" :
            zip(modifiers, mods).filter { $0.1 }.map { $0.0.symbol }.joined()
        return prefix + opt.legend
    }
}

struct KeymapError: LocalizedError {
    let message: String
    var errorDescription: String? { message }
}

// macOS smart-substitutes typographic characters while typing; fold the common
// ones back to ASCII instead of rejecting them.
private let asciiFolds: [Character: String] = [
    "\u{2019}": "'", "\u{2018}": "'", "\u{201A}": "'",
    "\u{201C}": "\"", "\u{201D}": "\"", "\u{201E}": "\"",
    "\u{2013}": "-", "\u{2014}": "-", "\u{2212}": "-",
    "\u{2026}": "...", "\u{00A0}": " ",
]

func cString(_ text: String) throws -> String {
    let folded = text.map { asciiFolds[$0] ?? String($0) }.joined()
    var out = "\""
    for ch in folded.unicodeScalars {
        switch ch {
        case "\\": out += "\\\\"
        case "\"": out += "\\\""
        case "\n": out += "\\n"
        case "\t": out += "\\t"
        case let c where c.value >= 32 && c.value < 127: out.unicodeScalars.append(c)
        default: throw KeymapError(message: "only plain ASCII can be typed, not '\(ch)'")
        }
    }
    return out + "\""
}

func macros(_ n: Int, _ spec: KeySpec) throws -> String {
    if spec.mode == .text {
        let literal = try cString(spec.text)
        return """
        #define KEY\(n)_PRESSED()  { KBD_print(\(literal)); }
        #define KEY\(n)_RELEASED() { }

        """
    }
    let opt = keyOption(spec.keyLabel)
    if opt.kind == .con {
        return """
        #define KEY\(n)_PRESSED()  { CON_press(\(opt.expr)); }
        #define KEY\(n)_RELEASED() { CON_release(\(opt.expr)); }

        """
    }
    let mods = zip(modifiers, spec.mods).filter { $0.1 }.map { $0.0.expr }
    let press = mods.map { "KBD_press(\($0)); " }.joined() + "KBD_press(\(opt.expr));"
    let release = "KBD_release(\(opt.expr));"
        + mods.reversed().map { " KBD_release(\($0));" }.joined()
    return """
    #define KEY\(n)_PRESSED()  { \(press) }
    #define KEY\(n)_RELEASED() { \(release) }

    """
}

func keymapFile(_ spec1: KeySpec, _ spec2: KeySpec) throws -> String {
    try "// Generated by the BitchBoy Nano flasher - do not edit by hand.\n\n#pragma once\n\n"
        + macros(1, spec1) + "\n" + macros(2, spec2)
}

func runCheck() throws {
    var s1 = KeySpec()
    s1.mods = [true, false, false, true]
    s1.keyLabel = "F13"
    var s2 = KeySpec(mode: .text)
    s2.text = "echo \"hi \\ there\"\nsecond line"

    let keymap = try keymapFile(s1, s2)
    assert(keymap.contains("KBD_press(KBD_KEY_LEFT_CTRL); KBD_press(KBD_KEY_LEFT_GUI); KBD_press(KBD_KEY_F13);"))
    assert(keymap.contains("KBD_release(KBD_KEY_F13); KBD_release(KBD_KEY_LEFT_GUI); KBD_release(KBD_KEY_LEFT_CTRL);"))
    assert(keymap.contains("KBD_print(\"echo \\\"hi \\\\ there\\\"\\nsecond line\");"))
    assert(s1.legend == "⌃⌘F13")
    assert((try? cString("héllo")) == nil, "non-ASCII should be rejected")
    assert(try! cString("Hi, I\u{2019}m \u{201C}Nano\u{201D} \u{2014} ok\u{2026}")
        == "\"Hi, I'm \\\"Nano\\\" - ok...\"")

    var media = KeySpec()
    media.keyLabel = "Volume Up"
    assert(try! macros(1, media).contains("CON_press(CON_VOL_UP)"))
    print("check OK: keymap generation verified")
}
