// Generated by the BitchBoy Nano flasher - do not edit by hand.

#pragma once

#define KEY1_PRESSED()  { KBD_print("claude\n"); }
#define KEY1_RELEASED() { }

#define KEY2_PRESSED()  { KBD_press(KBD_KEY_LEFT_CTRL); KBD_press(KBD_KEY_LEFT_SHIFT); KBD_press(KBD_KEY_LEFT_GUI); KBD_press('4'); }
#define KEY2_RELEASED() { KBD_release('4'); KBD_release(KBD_KEY_LEFT_GUI); KBD_release(KBD_KEY_LEFT_SHIFT); KBD_release(KBD_KEY_LEFT_CTRL); }

#define KEY1_LED_MODE      LED_MODE_CYCLE
#define KEY1_LED_G         0
#define KEY1_LED_B         255
#define KEY1_LED_PERIOD_MS 2500
#define KEY1_LED_PRESS     1
#define KEY1_LED_PRESS_G   255
#define KEY1_LED_PRESS_B   255

#define KEY2_LED_MODE      LED_MODE_BREATHE
#define KEY2_LED_G         0
#define KEY2_LED_B         255
#define KEY2_LED_PERIOD_MS 1800
#define KEY2_LED_PRESS     1
#define KEY2_LED_PRESS_G   255
#define KEY2_LED_PRESS_B   0
