// Generated by flasher.py - do not edit by hand, the GUI overwrites this file.
// Default map: key 1 = 'a', key 2 = 'b', held while the button is held.

#pragma once

#define KEY1_PRESSED()  { KBD_press('a'); }
#define KEY1_RELEASED() { KBD_release('a'); }

#define KEY2_PRESSED()  { KBD_press('b'); }
#define KEY2_RELEASED() { KBD_release('b'); }
