// ===================================================================================
// Project:   BitchBoy Nano - 2-key HID keypad for CH551, CH552, CH554
// License:   http://creativecommons.org/licenses/by-sa/3.0/
// ===================================================================================
//
// Turns a cheap CH552-based 2-key macropad into a plain USB HID keyboard. What each
// key sends, and how its LED behaves, lives in keymap.h, which is generated by the
// flasher GUI.
//
// Entering the bootloader: hold both keys while plugging in (or, from stock
// firmware, pull UDP to 3.3V through 10k while plugging in - see README).

#include <stdint.h>

#include "config.h"
#include "system.h"
#include "delay.h"
#include "gpio.h"
#include "usb_conkbd.h"
#include "keymap.h"

void USB_interrupt(void);
void USB_ISR(void) __interrupt(INT_NO_USB) {
  USB_interrupt();
}

#ifndef KEY1_LED_MODE
#define KEY1_LED_MODE      LED_MODE_OFF
#define KEY1_LED_G         0
#define KEY1_LED_B         0
#define KEY1_LED_PERIOD_MS 2000
#define KEY1_LED_PRESS     1
#define KEY1_LED_PRESS_G   255
#define KEY1_LED_PRESS_B   255
#endif

#ifndef KEY2_LED_MODE
#define KEY2_LED_MODE      LED_MODE_OFF
#define KEY2_LED_G         0
#define KEY2_LED_B         0
#define KEY2_LED_PERIOD_MS 2000
#define KEY2_LED_PRESS     1
#define KEY2_LED_PRESS_G   255
#define KEY2_LED_PRESS_B   255
#endif

// Animation runs off an 8-bit phase rather than the millisecond count directly, so a
// period only costs a division once at startup instead of every frame.
#define ANIM_STEP_MS(period) ((period) < 256 ? 1 : (period) / 256)

static uint8_t green1, blue1, green2, blue2;
static uint8_t phase1, phase2;
static uint16_t accum1, accum2;

static void LED_init(void) {
  PIN_low(KEY1_LED_ANODE);   PIN_output(KEY1_LED_ANODE);
  PIN_low(KEY2_LED_ANODE);   PIN_output(KEY2_LED_ANODE);
  PIN_high(KEY1_LED_GREEN);  PIN_output(KEY1_LED_GREEN);
  PIN_high(KEY1_LED_BLUE);   PIN_output(KEY1_LED_BLUE);
  PIN_high(KEY2_LED_GREEN);  PIN_output(KEY2_LED_GREEN);
  PIN_high(KEY2_LED_BLUE);   PIN_output(KEY2_LED_BLUE);
}

static uint8_t triangle(uint8_t p) {
  return p < 128 ? (p << 1) : ((255 - p) << 1);
}

static uint8_t scale(uint8_t value, uint8_t by) {
  return (uint8_t)(((uint16_t)value * by) >> 8);
}

static void mix(uint8_t mode, uint8_t p, uint8_t g, uint8_t b,
                uint8_t *outG, uint8_t *outB) {
  uint8_t wave;
  switch(mode) {
    case LED_MODE_SOLID:
      *outG = g; *outB = b;
      break;
    case LED_MODE_BREATHE:
      wave = triangle(p);
      *outG = scale(g, wave); *outB = scale(b, wave);
      break;
    case LED_MODE_CYCLE:
      wave = triangle(p);
      *outG = 255 - wave; *outB = wave;
      break;
    default:
      *outG = 0; *outB = 0;
      break;
  }
  *outG = scale(*outG, LED_BRIGHTNESS);
  *outB = scale(*outB, LED_BRIGHTNESS);
}

// One software-PWM period, roughly a millisecond. Cathodes sink, so a channel is lit
// while its line is held low. Both anodes are driven together; a key whose colour is
// fully off gets its anode dropped so nothing leaks through.
static void LED_render(void) {
  uint8_t step;
  uint8_t g1 = green1 >> 3, b1 = blue1 >> 3;
  uint8_t g2 = green2 >> 3, b2 = blue2 >> 3;

  PIN_write(KEY1_LED_ANODE, (green1 | blue1) != 0);
  PIN_write(KEY2_LED_ANODE, (green2 | blue2) != 0);

  for(step = 0; step < 32; step++) {
    PIN_write(KEY1_LED_GREEN, step >= g1);
    PIN_write(KEY1_LED_BLUE,  step >= b1);
    PIN_write(KEY2_LED_GREEN, step >= g2);
    PIN_write(KEY2_LED_BLUE,  step >= b2);
    DLY_us(20);
  }

  PIN_high(KEY1_LED_GREEN); PIN_high(KEY1_LED_BLUE);
  PIN_high(KEY2_LED_GREEN); PIN_high(KEY2_LED_BLUE);
}

void main(void) {
  __bit key1 = 0, key2 = 0, now;

  CLK_config();
  DLY_ms(5);

  PIN_input_PU(KEY1_PIN);
  PIN_input_PU(KEY2_PIN);
  DLY_ms(1);

  // Both keys held while plugging in -> jump straight to the bootloader.
  if(!PIN_read(KEY1_PIN) && !PIN_read(KEY2_PIN)) BOOT_now();

  KBD_init();
  LED_init();
  DLY_ms(10);

  while(1) {
    now = !PIN_read(KEY1_PIN);
    if(now != key1) {
      key1 = now;
      if(now) { KEY1_PRESSED(); } else { KEY1_RELEASED(); }
      DLY_ms(KEY_DEBOUNCE_MS);
    }

    now = !PIN_read(KEY2_PIN);
    if(now != key2) {
      key2 = now;
      if(now) { KEY2_PRESSED(); } else { KEY2_RELEASED(); }
      DLY_ms(KEY_DEBOUNCE_MS);
    }

    if(++accum1 >= ANIM_STEP_MS(KEY1_LED_PERIOD_MS)) { accum1 = 0; phase1++; }
    if(++accum2 >= ANIM_STEP_MS(KEY2_LED_PERIOD_MS)) { accum2 = 0; phase2++; }

    if(key1 && KEY1_LED_PRESS) {
      green1 = scale(KEY1_LED_PRESS_G, LED_BRIGHTNESS);
      blue1  = scale(KEY1_LED_PRESS_B, LED_BRIGHTNESS);
    } else {
      mix(KEY1_LED_MODE, phase1, KEY1_LED_G, KEY1_LED_B, &green1, &blue1);
    }

    if(key2 && KEY2_LED_PRESS) {
      green2 = scale(KEY2_LED_PRESS_G, LED_BRIGHTNESS);
      blue2  = scale(KEY2_LED_PRESS_B, LED_BRIGHTNESS);
    } else {
      mix(KEY2_LED_MODE, phase2, KEY2_LED_G, KEY2_LED_B, &green2, &blue2);
    }

    LED_render();
  }
}
