// ===================================================================================
// Project:   BitchBoy Nano - 2-key HID keypad for CH551, CH552, CH554
// License:   http://creativecommons.org/licenses/by-sa/3.0/
// ===================================================================================
//
// Turns a cheap CH552-based 2-key macropad into a plain USB HID keyboard. What each
// key sends lives in keymap.h, which is generated by the flasher GUI.
//
// Entering the bootloader: hold both keys while plugging in (or, from stock
// firmware, pull UDP to 3.3V through 10k while plugging in - see README).

#include "config.h"
#include "system.h"
#include "delay.h"
#include "gpio.h"
#include "usb_conkbd.h"
#include "keymap.h"

void USB_interrupt(void);
void USB_ISR(void) __interrupt(INT_NO_USB) {
  USB_interrupt();
}

void main(void) {
  __bit key1 = 0, key2 = 0, now;

  CLK_config();
  DLY_ms(5);

  PIN_input_PU(KEY1_PIN);
  PIN_input_PU(KEY2_PIN);
  DLY_ms(1);                                // let the pull-ups settle

  // Both keys held while plugging in -> jump straight to the bootloader.
  if(!PIN_read(KEY1_PIN) && !PIN_read(KEY2_PIN)) BOOT_now();

  KBD_init();
  DLY_ms(10);

  while(1) {
    now = !PIN_read(KEY1_PIN);
    if(now != key1) {
      key1 = now;
      if(now) { KEY1_PRESSED(); } else { KEY1_RELEASED(); }
      DLY_ms(KEY_DEBOUNCE_MS);
    }

    now = !PIN_read(KEY2_PIN);
    if(now != key2) {
      key2 = now;
      if(now) { KEY2_PRESSED(); } else { KEY2_RELEASED(); }
      DLY_ms(KEY_DEBOUNCE_MS);
    }

    DLY_ms(2);
  }
}
